// Copyright 2024 Maicol Castro (maicolcastro.abc@gmail.com).
// Distributed under the BSD 3-Clause License.
// See LICENSE.txt in the root directory of this project
// or at https://opensource.org/license/bsd-3-clause.

#pragma once

namespace Luna::Engine::Game {

enum eGameAddr {
    GAME_ADDR_PLAYERS = 0x6883C0,

    GAME_ADDR_POINTS = 0x6E707C,
    GAME_ADDR_LIB_INPUTEVENT = 0x277B79,
    GAME_ADDR_OS_KEYBOARDREQUEST = 0x278A09,
    GAME_ADDR_KEYBOARDWASVISIBLE = 0x6E702C,
    
    GAME_ADDR_CHUD_DRAWAFTERFADE = 0x44A6A9,

    GAME_ADDR_CTASK_OPERATOR_NEW = 0x4E6A71,
    GAME_ADDR_CTASKCOMPLEXDIE_CONSTRUCTOR = 0x4FB5E1,
    GAME_ADDR_CTASKMANAGER_SETTASK = 0x54397B,
    GAME_ADDR_CTASKSIMPLEPLAYERONFOOT_CONSTRUCTOR = 0x547551,

    GAME_ADDR_CPAD_DIVEJUSTDOWN = 0x40BD11,
    GAME_ADDR_CPAD_DUCKJUSTDOWN = 0x40BA9D,
    GAME_ADDR_CPAD_EXITVEHICLEJUSTDOWN = 0x40AA7D,
    GAME_ADDR_CPAD_GETABORTCLIMB = 0x40BBB9,
    GAME_ADDR_CPAD_GETACCELERATE = 0x40B351,
    GAME_ADDR_CPAD_GETAUTOCLIMB = 0x40BB0D,
    GAME_ADDR_CPAD_GETBLOCK = 0x19E0FC,
    GAME_ADDR_CPAD_GETBRAKE = 0x40A9AD,
    GAME_ADDR_CPAD_GETHANDBRAKE = 0x40A7E1,
    GAME_ADDR_CPAD_GETHORN = 0x40A619,
    GAME_ADDR_CPAD_GETJUMP = 0x40BC59,
    GAME_ADDR_CPAD_GETPEDWALKLEFTRIGHT = 0x40A219,
    GAME_ADDR_CPAD_GETPEDWALKUPDOWN = 0x40A299,
    GAME_ADDR_CPAD_GETSPRINT = 0x40BDB1,
    GAME_ADDR_CPAD_GETSTEERINGLEFTRIGHT = 0x409B55,
    GAME_ADDR_CPAD_GETSTEERINGUPDOWN = 0x409D25,
    GAME_ADDR_CPAD_JUMPJUSTDOWN = 0x40BCAD,
    GAME_ADDR_CPAD_MELEEATTACKJUSTDOWN = 0x1A2AB0,
    GAME_ADDR_CPAD_SWIMJUMPJUSTDOWN = 0x40BD59,

    GAME_ADDR_CPLAYERPED_CONSTRUCTOR = 0x4D367D,
    GAME_ADDR_CPLAYERPED_DESTRUCTOR = 0x4D3901,
    GAME_ADDR_CPLAYERPED_GETPLAYERINFOFORTHISPLAYERPED = 0x4D99CD,
    GAME_ADDR_CPLAYERPED_PROCESSCONTROL = 0x4D47E9,
    GAME_ADDR_CPLAYERPED_SETUPPLAYERPED = 0x4D39A5,

    GAME_ADDR_CRADAR_DRAWAREAONRADAR = 0x453C61,
    GAME_ADDR_CRADAR_CHANGEBLIPSCALE = 0x452B11,
    GAME_ADDR_CRADAR_CHANGEBLIPCOLOUR = 0x452A59,
    GAME_ADDR_CRADAR_SETCOORDBLIP = 0x452771,

    GAME_ADDR_CMESSAGES_ADDBIGMESSAGE = 0x55C62D,
};

} // namespace Luna::Engine::Game
